# Generated by Django 5.2.8 on 2025-11-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_alter_pipeline_geojson_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("backscatter_threshold", "Backscatter Thresholding"),
                    ("glcm_texture", "GLCM Texture Analysis"),
                    ("polarimetric_decomp", "Polarimetric Decomposition"),
                    ("time_series", "Time-series Tracking"),
                    ("insar", "InSAR"),
                    ("dinsar", "DInSAR"),
                    ("psinsar", "PS-InSAR"),
                    ("sbas_insar", "SBAS-InSAR"),
                    ("phase_unwrap", "Phase Unwrapping"),
                    ("atmospheric_corr", "Atmospheric Correction"),
                    ("cfar", "CFAR Detection"),
                    ("polarimetric_scatter", "Polarimetric Scattering Analysis"),
                    ("texture_shape", "Texture/Shape Metrics"),
                    ("coherence_change", "Coherence Change Detection"),
                    ("deep_learning", "Deep Learning Analysis"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="anomaly_type",
            field=models.CharField(
                choices=[
                    ("displacement", "Ground Displacement"),
                    ("subsidence", "Subsidence"),
                    ("deformation", "Surface Deformation"),
                    ("scattering_change", "Scattering Pattern Change"),
                    ("coherence_loss", "Coherence Loss"),
                    ("texture_anomaly", "Texture Anomaly"),
                    ("phase_anomaly", "Phase Anomaly"),
                    ("intensity_change", "Intensity Change"),
                    ("structural_change", "Structural Change"),
                    ("temporal_anomaly", "Temporal Anomaly"),
                ],
                max_length=50,
            ),
        ),
    ]
