# Generated by Django 5.2.8 on 2025-11-14 08:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_alter_analysis_analysis_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("backscatter_threshold", "Backscatter Thresholding"),
                    ("glcm_texture", "GLCM Texture Analysis"),
                    ("polarimetric_decomp", "Polarimetric Decomposition"),
                    ("time_series", "Time-series Tracking"),
                    ("insar", "InSAR"),
                    ("dinsar", "DInSAR"),
                    ("psinsar", "PS-InSAR"),
                    ("sbas_insar", "SBAS-InSAR"),
                    ("phase_unwrap", "Phase Unwrapping"),
                    ("atmospheric_corr", "Atmospheric Correction"),
                    ("cfar", "CFAR Detection"),
                    ("polarimetric_scatter", "Polarimetric Scattering Analysis"),
                    ("texture_shape", "Texture/Shape Metrics"),
                    ("coherence_change", "Coherence Change Detection"),
                    ("deep_learning", "Deep Learning Analysis"),
                    ("object_identification", "Object Identification"),
                    ("oil_spill_detection", "Oil Spill Detection"),
                    ("pipeline_encroachment", "Pipeline Encroachment"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="LegendCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Category name (e.g., "Oil Spill", "Building", "Vegetation")',
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FF0000",
                        help_text="Hex color code for this category (e.g., #FF0000 for red)",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name or emoji for this category",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("oil_spill", "Oil Spill"),
                            ("encroachment", "Pipeline Encroachment"),
                            ("infrastructure", "Infrastructure"),
                            ("vegetation", "Vegetation"),
                            ("water_body", "Water Body"),
                            ("building", "Building"),
                            ("vehicle", "Vehicle"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Legend Category",
                "verbose_name_plural": "Legend Categories",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="MappedObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/identifier for this mapped object",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "geojson_file",
                    models.FileField(
                        help_text="Upload a GeoJSON file containing the mapped object geometry",
                        upload_to="mapped_objects/geojson/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["json", "geojson"]
                            )
                        ],
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("oil_spill", "Oil Spill"),
                            ("encroachment", "Pipeline Encroachment"),
                            ("building", "Building"),
                            ("vehicle", "Vehicle"),
                            ("infrastructure", "Infrastructure"),
                            ("vegetation", "Vegetation"),
                            ("water_body", "Water Body"),
                            ("unknown", "Unknown/Other"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "area_m2",
                    models.FloatField(
                        blank=True, help_text="Area in square meters", null=True
                    ),
                ),
                (
                    "perimeter_m",
                    models.FloatField(
                        blank=True, help_text="Perimeter in meters", null=True
                    ),
                ),
                ("centroid_lat", models.FloatField(blank=True, null=True)),
                ("centroid_lon", models.FloatField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score (0-1) if identified by AI",
                        null=True,
                    ),
                ),
                (
                    "identified_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Mapping"),
                            ("ai", "AI Detection"),
                            ("hybrid", "Hybrid (AI + Manual)"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Verified by expert"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legend_category",
                    models.ForeignKey(
                        help_text="Legend category for this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mapped_objects",
                        to="monitoring.legendcategory",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated pipeline (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapped_objects",
                        to="monitoring.pipeline",
                    ),
                ),
                (
                    "satellite_image",
                    models.ForeignKey(
                        help_text="The satellite image this object was mapped on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapped_objects",
                        to="monitoring.satelliteimage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapped_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapped Object",
                "verbose_name_plural": "Mapped Objects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="analysis",
            name="mapped_objects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Mapped objects associated with this analysis",
                related_name="analyses",
                to="monitoring.mappedobject",
            ),
        ),
        migrations.AddIndex(
            model_name="mappedobject",
            index=models.Index(
                fields=["user", "satellite_image"],
                name="monitoring__user_id_0bfaf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mappedobject",
            index=models.Index(
                fields=["object_type", "created_at"],
                name="monitoring__object__e06a4b_idx",
            ),
        ),
    ]
