# Generated by Django 5.2.8 on 2025-11-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_alter_analysis_analysis_type_legendcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("backscatter_threshold", "Backscatter Thresholding"),
                    ("glcm_texture", "GLCM Texture Analysis"),
                    ("polarimetric_decomp", "Polarimetric Decomposition"),
                    ("time_series", "Time-series Tracking"),
                    ("insar", "InSAR"),
                    ("dinsar", "DInSAR"),
                    ("psinsar", "PS-InSAR"),
                    ("sbas_insar", "SBAS-InSAR"),
                    ("phase_unwrap", "Phase Unwrapping"),
                    ("atmospheric_corr", "Atmospheric Correction"),
                    ("cfar", "CFAR Detection"),
                    ("polarimetric_scatter", "Polarimetric Scattering Analysis"),
                    ("texture_shape", "Texture/Shape Metrics"),
                    ("coherence_change", "Coherence Change Detection"),
                    ("deep_learning", "Deep Learning Analysis"),
                    ("object_identification", "Object Identification"),
                ],
                max_length=50,
            ),
        ),
    ]
